package com.zurich.cpc.model.pk;
// default package
// Generated 2013/10/25 �U�� 06:01:44 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppGtlMTbId generated by hbm2java
 */
@Embeddable
public class AppGtlMId_bk implements Serializable {

    private static final long serialVersionUID = 2512687888303597849L;

    @Column(name = "Data_ID", updatable = false)
    private String dataId;

    @Column(name = "Data_ID_VerNo", updatable = false)
    private short dataIdVerNo;
    
    public AppGtlMId_bk() {
    }

    public short getDataIdVerNo() {
        return this.dataIdVerNo;
    }

    public void setDataIdVerNo(short dataIdVerNo) {
        this.dataIdVerNo = dataIdVerNo;
    }
    
	public String getDataId() {
		return dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}
    
}
