package com.zurich.cpc.model;

// Generated 2014/6/18 ¤U¤È 04:24:04 by Hibernate Tools 3.4.0.CR1

/**
 * AppGtlMTbId generated by hbm2java
 */
public class AppGtlMTbId implements java.io.Serializable {

	private String dataId;
	private short dataIdVerNo;

	public AppGtlMTbId() {
	}

	public AppGtlMTbId(String dataId, short dataIdVerNo) {
		this.dataId = dataId;
		this.dataIdVerNo = dataIdVerNo;
	}

	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	public short getDataIdVerNo() {
		return this.dataIdVerNo;
	}

	public void setDataIdVerNo(short dataIdVerNo) {
		this.dataIdVerNo = dataIdVerNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppGtlMTbId))
			return false;
		AppGtlMTbId castOther = (AppGtlMTbId) other;

		return ((this.getDataId() == castOther.getDataId()) || (this
				.getDataId() != null && castOther.getDataId() != null && this
				.getDataId().equals(castOther.getDataId())))
				&& (this.getDataIdVerNo() == castOther.getDataIdVerNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDataId() == null ? 0 : this.getDataId().hashCode());
		result = 37 * result + this.getDataIdVerNo();
		return result;
	}

}
