package com.zurich.cpc.model;

// Generated 2014/6/18 ¤U¤È 04:24:04 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AppMTb generated by hbm2java
 */
public class AppMTb implements java.io.Serializable {

	private String dataId;
	private String dataSrcCd;
	private String prdtCd;
	private String cmpgnCd;
	private String pkgeCd;
	private Integer insuredCustNo;
	private Integer applicantCustNo;
	private Integer payerCustNo;
	private Integer receiverCustNo;
	private String chlCd;
	private String busUnitCd;
	private String agntCd;
	private String agntKindCd;
	private String agntId;
	private String agntNm;
	private String agntEmail;
	private String agntGrpNm;
	private String intrAgntCd;
	private String intrAgntId;
	private String intrAgntNm;
	private String intrAgntEmail;
	private String salesCd;
	private String salesId;
	private String salesNm;
	private String salesEmail;
	private String refCalcChnl;
	private String collectId;
	private String issueBrhCd;
	private String distChlCd;
	private String tgtMktCd;
	private Character sbu;
	private Date insEffDt;
	private Date insExpDt;
	private String insEffTm;
	private String insExpTm;
	private String insDtTm;
	private Date incomeDt;
	private String incomeId;
	private String hostProjCd;
	private String hostPkgeCd;
	private Integer totalPrm;
	private Character allowModMk;
	private Character zautoContactMk;
	private String elecDocuNm;
	private Character elecDocuCreateMk;
	private Date elecDocuCreateDt;
	private String chlDataNo;
	private Integer chlDataTranNo;
	private String chlUserGrpCd;
	private String contactWinNm;
	private String contactWinWay;
	private String contactWinEmail;
	private String oriDataId;
	private Character quotMk;
	private Character inviteMk;
	private Character autoUwMk;
	private Character manualUwMk;
	private Character cancelMk;
	private Character paymntMk;
	private Character issueMk;
	private Character issueCaMk;
	private String hostPaymntMthdCd;
	private Character settlementFreqCd;
	private Character ownCostMk;
	private String paymntEncodeAcnt;
	private String paymntCardExpYm;
	private Character paymntResultMk;
	private Date paymntTransDt;
	private String paymntQuest;
	private String paymntAns;
	private String ncccReplyMsg;
	private Integer ncccTranSeq;
	private Set appPdMTbs = new HashSet(0);

	public AppMTb() {
	}

	public AppMTb(String dataId, String dataSrcCd, String prdtCd) {
		this.dataId = dataId;
		this.dataSrcCd = dataSrcCd;
		this.prdtCd = prdtCd;
	}

	public AppMTb(String dataId, String dataSrcCd, String prdtCd,
			String cmpgnCd, String pkgeCd, Integer insuredCustNo,
			Integer applicantCustNo, Integer payerCustNo,
			Integer receiverCustNo, String chlCd, String busUnitCd,
			String agntCd, String agntKindCd, String agntId, String agntNm,
			String agntEmail, String agntGrpNm, String intrAgntCd,
			String intrAgntId, String intrAgntNm, String intrAgntEmail,
			String salesCd, String salesId, String salesNm, String salesEmail,
			String refCalcChnl, String collectId, String issueBrhCd,
			String distChlCd, String tgtMktCd, Character sbu, Date insEffDt,
			Date insExpDt, String insEffTm, String insExpTm, String insDtTm,
			Date incomeDt, String incomeId, String hostProjCd,
			String hostPkgeCd, Integer totalPrm, Character allowModMk,
			Character zautoContactMk, String elecDocuNm,
			Character elecDocuCreateMk, Date elecDocuCreateDt,
			String chlDataNo, Integer chlDataTranNo, String chlUserGrpCd,
			String contactWinNm, String contactWinWay, String contactWinEmail,
			String oriDataId, Character quotMk, Character inviteMk,
			Character autoUwMk, Character manualUwMk, Character cancelMk,
			Character paymntMk, Character issueMk, Character issueCaMk,
			String hostPaymntMthdCd, Character settlementFreqCd,
			Character ownCostMk, String paymntEncodeAcnt,
			String paymntCardExpYm, Character paymntResultMk,
			Date paymntTransDt, String paymntQuest, String paymntAns,
			String ncccReplyMsg, Integer ncccTranSeq, Set appPdMTbs) {
		this.dataId = dataId;
		this.dataSrcCd = dataSrcCd;
		this.prdtCd = prdtCd;
		this.cmpgnCd = cmpgnCd;
		this.pkgeCd = pkgeCd;
		this.insuredCustNo = insuredCustNo;
		this.applicantCustNo = applicantCustNo;
		this.payerCustNo = payerCustNo;
		this.receiverCustNo = receiverCustNo;
		this.chlCd = chlCd;
		this.busUnitCd = busUnitCd;
		this.agntCd = agntCd;
		this.agntKindCd = agntKindCd;
		this.agntId = agntId;
		this.agntNm = agntNm;
		this.agntEmail = agntEmail;
		this.agntGrpNm = agntGrpNm;
		this.intrAgntCd = intrAgntCd;
		this.intrAgntId = intrAgntId;
		this.intrAgntNm = intrAgntNm;
		this.intrAgntEmail = intrAgntEmail;
		this.salesCd = salesCd;
		this.salesId = salesId;
		this.salesNm = salesNm;
		this.salesEmail = salesEmail;
		this.refCalcChnl = refCalcChnl;
		this.collectId = collectId;
		this.issueBrhCd = issueBrhCd;
		this.distChlCd = distChlCd;
		this.tgtMktCd = tgtMktCd;
		this.sbu = sbu;
		this.insEffDt = insEffDt;
		this.insExpDt = insExpDt;
		this.insEffTm = insEffTm;
		this.insExpTm = insExpTm;
		this.insDtTm = insDtTm;
		this.incomeDt = incomeDt;
		this.incomeId = incomeId;
		this.hostProjCd = hostProjCd;
		this.hostPkgeCd = hostPkgeCd;
		this.totalPrm = totalPrm;
		this.allowModMk = allowModMk;
		this.zautoContactMk = zautoContactMk;
		this.elecDocuNm = elecDocuNm;
		this.elecDocuCreateMk = elecDocuCreateMk;
		this.elecDocuCreateDt = elecDocuCreateDt;
		this.chlDataNo = chlDataNo;
		this.chlDataTranNo = chlDataTranNo;
		this.chlUserGrpCd = chlUserGrpCd;
		this.contactWinNm = contactWinNm;
		this.contactWinWay = contactWinWay;
		this.contactWinEmail = contactWinEmail;
		this.oriDataId = oriDataId;
		this.quotMk = quotMk;
		this.inviteMk = inviteMk;
		this.autoUwMk = autoUwMk;
		this.manualUwMk = manualUwMk;
		this.cancelMk = cancelMk;
		this.paymntMk = paymntMk;
		this.issueMk = issueMk;
		this.issueCaMk = issueCaMk;
		this.hostPaymntMthdCd = hostPaymntMthdCd;
		this.settlementFreqCd = settlementFreqCd;
		this.ownCostMk = ownCostMk;
		this.paymntEncodeAcnt = paymntEncodeAcnt;
		this.paymntCardExpYm = paymntCardExpYm;
		this.paymntResultMk = paymntResultMk;
		this.paymntTransDt = paymntTransDt;
		this.paymntQuest = paymntQuest;
		this.paymntAns = paymntAns;
		this.ncccReplyMsg = ncccReplyMsg;
		this.ncccTranSeq = ncccTranSeq;
		this.appPdMTbs = appPdMTbs;
	}

	public String getDataId() {
		return this.dataId;
	}

	public void setDataId(String dataId) {
		this.dataId = dataId;
	}

	public String getDataSrcCd() {
		return this.dataSrcCd;
	}

	public void setDataSrcCd(String dataSrcCd) {
		this.dataSrcCd = dataSrcCd;
	}

	public String getPrdtCd() {
		return this.prdtCd;
	}

	public void setPrdtCd(String prdtCd) {
		this.prdtCd = prdtCd;
	}

	public String getCmpgnCd() {
		return this.cmpgnCd;
	}

	public void setCmpgnCd(String cmpgnCd) {
		this.cmpgnCd = cmpgnCd;
	}

	public String getPkgeCd() {
		return this.pkgeCd;
	}

	public void setPkgeCd(String pkgeCd) {
		this.pkgeCd = pkgeCd;
	}

	public Integer getInsuredCustNo() {
		return this.insuredCustNo;
	}

	public void setInsuredCustNo(Integer insuredCustNo) {
		this.insuredCustNo = insuredCustNo;
	}

	public Integer getApplicantCustNo() {
		return this.applicantCustNo;
	}

	public void setApplicantCustNo(Integer applicantCustNo) {
		this.applicantCustNo = applicantCustNo;
	}

	public Integer getPayerCustNo() {
		return this.payerCustNo;
	}

	public void setPayerCustNo(Integer payerCustNo) {
		this.payerCustNo = payerCustNo;
	}

	public Integer getReceiverCustNo() {
		return this.receiverCustNo;
	}

	public void setReceiverCustNo(Integer receiverCustNo) {
		this.receiverCustNo = receiverCustNo;
	}

	public String getChlCd() {
		return this.chlCd;
	}

	public void setChlCd(String chlCd) {
		this.chlCd = chlCd;
	}

	public String getBusUnitCd() {
		return this.busUnitCd;
	}

	public void setBusUnitCd(String busUnitCd) {
		this.busUnitCd = busUnitCd;
	}

	public String getAgntCd() {
		return this.agntCd;
	}

	public void setAgntCd(String agntCd) {
		this.agntCd = agntCd;
	}

	public String getAgntKindCd() {
		return this.agntKindCd;
	}

	public void setAgntKindCd(String agntKindCd) {
		this.agntKindCd = agntKindCd;
	}

	public String getAgntId() {
		return this.agntId;
	}

	public void setAgntId(String agntId) {
		this.agntId = agntId;
	}

	public String getAgntNm() {
		return this.agntNm;
	}

	public void setAgntNm(String agntNm) {
		this.agntNm = agntNm;
	}

	public String getAgntEmail() {
		return this.agntEmail;
	}

	public void setAgntEmail(String agntEmail) {
		this.agntEmail = agntEmail;
	}

	public String getAgntGrpNm() {
		return this.agntGrpNm;
	}

	public void setAgntGrpNm(String agntGrpNm) {
		this.agntGrpNm = agntGrpNm;
	}

	public String getIntrAgntCd() {
		return this.intrAgntCd;
	}

	public void setIntrAgntCd(String intrAgntCd) {
		this.intrAgntCd = intrAgntCd;
	}

	public String getIntrAgntId() {
		return this.intrAgntId;
	}

	public void setIntrAgntId(String intrAgntId) {
		this.intrAgntId = intrAgntId;
	}

	public String getIntrAgntNm() {
		return this.intrAgntNm;
	}

	public void setIntrAgntNm(String intrAgntNm) {
		this.intrAgntNm = intrAgntNm;
	}

	public String getIntrAgntEmail() {
		return this.intrAgntEmail;
	}

	public void setIntrAgntEmail(String intrAgntEmail) {
		this.intrAgntEmail = intrAgntEmail;
	}

	public String getSalesCd() {
		return this.salesCd;
	}

	public void setSalesCd(String salesCd) {
		this.salesCd = salesCd;
	}

	public String getSalesId() {
		return this.salesId;
	}

	public void setSalesId(String salesId) {
		this.salesId = salesId;
	}

	public String getSalesNm() {
		return this.salesNm;
	}

	public void setSalesNm(String salesNm) {
		this.salesNm = salesNm;
	}

	public String getSalesEmail() {
		return this.salesEmail;
	}

	public void setSalesEmail(String salesEmail) {
		this.salesEmail = salesEmail;
	}

	public String getRefCalcChnl() {
		return this.refCalcChnl;
	}

	public void setRefCalcChnl(String refCalcChnl) {
		this.refCalcChnl = refCalcChnl;
	}

	public String getCollectId() {
		return this.collectId;
	}

	public void setCollectId(String collectId) {
		this.collectId = collectId;
	}

	public String getIssueBrhCd() {
		return this.issueBrhCd;
	}

	public void setIssueBrhCd(String issueBrhCd) {
		this.issueBrhCd = issueBrhCd;
	}

	public String getDistChlCd() {
		return this.distChlCd;
	}

	public void setDistChlCd(String distChlCd) {
		this.distChlCd = distChlCd;
	}

	public String getTgtMktCd() {
		return this.tgtMktCd;
	}

	public void setTgtMktCd(String tgtMktCd) {
		this.tgtMktCd = tgtMktCd;
	}

	public Character getSbu() {
		return this.sbu;
	}

	public void setSbu(Character sbu) {
		this.sbu = sbu;
	}

	public Date getInsEffDt() {
		return this.insEffDt;
	}

	public void setInsEffDt(Date insEffDt) {
		this.insEffDt = insEffDt;
	}

	public Date getInsExpDt() {
		return this.insExpDt;
	}

	public void setInsExpDt(Date insExpDt) {
		this.insExpDt = insExpDt;
	}

	public String getInsEffTm() {
		return this.insEffTm;
	}

	public void setInsEffTm(String insEffTm) {
		this.insEffTm = insEffTm;
	}

	public String getInsExpTm() {
		return this.insExpTm;
	}

	public void setInsExpTm(String insExpTm) {
		this.insExpTm = insExpTm;
	}

	public String getInsDtTm() {
		return this.insDtTm;
	}

	public void setInsDtTm(String insDtTm) {
		this.insDtTm = insDtTm;
	}

	public Date getIncomeDt() {
		return this.incomeDt;
	}

	public void setIncomeDt(Date incomeDt) {
		this.incomeDt = incomeDt;
	}

	public String getIncomeId() {
		return this.incomeId;
	}

	public void setIncomeId(String incomeId) {
		this.incomeId = incomeId;
	}

	public String getHostProjCd() {
		return this.hostProjCd;
	}

	public void setHostProjCd(String hostProjCd) {
		this.hostProjCd = hostProjCd;
	}

	public String getHostPkgeCd() {
		return this.hostPkgeCd;
	}

	public void setHostPkgeCd(String hostPkgeCd) {
		this.hostPkgeCd = hostPkgeCd;
	}

	public Integer getTotalPrm() {
		return this.totalPrm;
	}

	public void setTotalPrm(Integer totalPrm) {
		this.totalPrm = totalPrm;
	}

	public Character getAllowModMk() {
		return this.allowModMk;
	}

	public void setAllowModMk(Character allowModMk) {
		this.allowModMk = allowModMk;
	}

	public Character getZautoContactMk() {
		return this.zautoContactMk;
	}

	public void setZautoContactMk(Character zautoContactMk) {
		this.zautoContactMk = zautoContactMk;
	}

	public String getElecDocuNm() {
		return this.elecDocuNm;
	}

	public void setElecDocuNm(String elecDocuNm) {
		this.elecDocuNm = elecDocuNm;
	}

	public Character getElecDocuCreateMk() {
		return this.elecDocuCreateMk;
	}

	public void setElecDocuCreateMk(Character elecDocuCreateMk) {
		this.elecDocuCreateMk = elecDocuCreateMk;
	}

	public Date getElecDocuCreateDt() {
		return this.elecDocuCreateDt;
	}

	public void setElecDocuCreateDt(Date elecDocuCreateDt) {
		this.elecDocuCreateDt = elecDocuCreateDt;
	}

	public String getChlDataNo() {
		return this.chlDataNo;
	}

	public void setChlDataNo(String chlDataNo) {
		this.chlDataNo = chlDataNo;
	}

	public Integer getChlDataTranNo() {
		return this.chlDataTranNo;
	}

	public void setChlDataTranNo(Integer chlDataTranNo) {
		this.chlDataTranNo = chlDataTranNo;
	}

	public String getChlUserGrpCd() {
		return this.chlUserGrpCd;
	}

	public void setChlUserGrpCd(String chlUserGrpCd) {
		this.chlUserGrpCd = chlUserGrpCd;
	}

	public String getContactWinNm() {
		return this.contactWinNm;
	}

	public void setContactWinNm(String contactWinNm) {
		this.contactWinNm = contactWinNm;
	}

	public String getContactWinWay() {
		return this.contactWinWay;
	}

	public void setContactWinWay(String contactWinWay) {
		this.contactWinWay = contactWinWay;
	}

	public String getContactWinEmail() {
		return this.contactWinEmail;
	}

	public void setContactWinEmail(String contactWinEmail) {
		this.contactWinEmail = contactWinEmail;
	}

	public String getOriDataId() {
		return this.oriDataId;
	}

	public void setOriDataId(String oriDataId) {
		this.oriDataId = oriDataId;
	}

	public Character getQuotMk() {
		return this.quotMk;
	}

	public void setQuotMk(Character quotMk) {
		this.quotMk = quotMk;
	}

	public Character getInviteMk() {
		return this.inviteMk;
	}

	public void setInviteMk(Character inviteMk) {
		this.inviteMk = inviteMk;
	}

	public Character getAutoUwMk() {
		return this.autoUwMk;
	}

	public void setAutoUwMk(Character autoUwMk) {
		this.autoUwMk = autoUwMk;
	}

	public Character getManualUwMk() {
		return this.manualUwMk;
	}

	public void setManualUwMk(Character manualUwMk) {
		this.manualUwMk = manualUwMk;
	}

	public Character getCancelMk() {
		return this.cancelMk;
	}

	public void setCancelMk(Character cancelMk) {
		this.cancelMk = cancelMk;
	}

	public Character getPaymntMk() {
		return this.paymntMk;
	}

	public void setPaymntMk(Character paymntMk) {
		this.paymntMk = paymntMk;
	}

	public Character getIssueMk() {
		return this.issueMk;
	}

	public void setIssueMk(Character issueMk) {
		this.issueMk = issueMk;
	}

	public Character getIssueCaMk() {
		return this.issueCaMk;
	}

	public void setIssueCaMk(Character issueCaMk) {
		this.issueCaMk = issueCaMk;
	}

	public String getHostPaymntMthdCd() {
		return this.hostPaymntMthdCd;
	}

	public void setHostPaymntMthdCd(String hostPaymntMthdCd) {
		this.hostPaymntMthdCd = hostPaymntMthdCd;
	}

	public Character getSettlementFreqCd() {
		return this.settlementFreqCd;
	}

	public void setSettlementFreqCd(Character settlementFreqCd) {
		this.settlementFreqCd = settlementFreqCd;
	}

	public Character getOwnCostMk() {
		return this.ownCostMk;
	}

	public void setOwnCostMk(Character ownCostMk) {
		this.ownCostMk = ownCostMk;
	}

	public String getPaymntEncodeAcnt() {
		return this.paymntEncodeAcnt;
	}

	public void setPaymntEncodeAcnt(String paymntEncodeAcnt) {
		this.paymntEncodeAcnt = paymntEncodeAcnt;
	}

	public String getPaymntCardExpYm() {
		return this.paymntCardExpYm;
	}

	public void setPaymntCardExpYm(String paymntCardExpYm) {
		this.paymntCardExpYm = paymntCardExpYm;
	}

	public Character getPaymntResultMk() {
		return this.paymntResultMk;
	}

	public void setPaymntResultMk(Character paymntResultMk) {
		this.paymntResultMk = paymntResultMk;
	}

	public Date getPaymntTransDt() {
		return this.paymntTransDt;
	}

	public void setPaymntTransDt(Date paymntTransDt) {
		this.paymntTransDt = paymntTransDt;
	}

	public String getPaymntQuest() {
		return this.paymntQuest;
	}

	public void setPaymntQuest(String paymntQuest) {
		this.paymntQuest = paymntQuest;
	}

	public String getPaymntAns() {
		return this.paymntAns;
	}

	public void setPaymntAns(String paymntAns) {
		this.paymntAns = paymntAns;
	}

	public String getNcccReplyMsg() {
		return this.ncccReplyMsg;
	}

	public void setNcccReplyMsg(String ncccReplyMsg) {
		this.ncccReplyMsg = ncccReplyMsg;
	}

	public Integer getNcccTranSeq() {
		return this.ncccTranSeq;
	}

	public void setNcccTranSeq(Integer ncccTranSeq) {
		this.ncccTranSeq = ncccTranSeq;
	}

	public Set getAppPdMTbs() {
		return this.appPdMTbs;
	}

	public void setAppPdMTbs(Set appPdMTbs) {
		this.appPdMTbs = appPdMTbs;
	}

}
